- autoload/dashboard.vim
This request disable wrap for dashboard buffer, so with a tiny window the elements still remains right.
> Disable wrap for dashboard buffer

- autoload/dashboard/fzf.vim
- plugin/dashboard.vim
This is how my fzf window (triggered with :Files) usually looks like:
But after installing `dashboard-nvim`, if I trigger fzf through it, for example by pressing enter on `Find file` or `Recently opened files` at the dashboard screen, `dashboard-nvim` overrides my fzf appearance and layout related config to make it look like this:
I found that very inconvenient. So, I removed these lines from `autoload/dashboard/fzf.vim` to preserve my fzf layout config. I tested this fix out, and it didn't break anything AFAIK.
PS: I think I noticed it checks if `g:dashboard_fzf_window` equals `1` before overriding my config. So, I tried setting it to `0`, but this didn't fix it.
> Respect user predefined fzf layout config

- plugin/dashboard.vim
This PR adds an `VimResized` autocmd to redraw dashboard when the window is resized, which fixes #49 and the [centering issue](https://github.com/glepnir/dashboard-nvim/issues/11#issuecomment-718596775) mentioned in #11. On neovim-qt, `dashboard#instance(0)` will be called multiple times on startup (4 times in my case), but after that it will be called once per `VimResized`.
> fix: #49 and neovim-qt issue as mentioned in #11

- autoload/dashboard.vim
Hi @glepnir 
I would like to create a PR to fix packer path in `dashboard.vim`
According to packer's [README.md](https://github.com/wbthomason/packer.nvim#quickstart)
The installed path should be `~/.local/share/nvim/site/pack/packer/start/packer.nvim`
Thanks!
Alex
> fix packer path for footer loader

- doc/dashboard.txt
`dashboardReady` will not work in an autocmd
> fix DashboardReady typo in docs

- autoload/dashboard/utils.vim
Allows the dashboard to be centered within vertical splits, and will automatically realign when the vim window is resized (on the VimResize event).
Couldn't figure out a way to get it to automatically realign when the splits are resized, as their doesn't seem to be an event for that.
> Center in vertical splits

- autoload/dashboard.vim
Packer.nvim is written by lua so that it cannot be used in vim now. And only neovim has the function stdpath. We need block the operation that detect Packer.nvim in vim.
> [Fix up] fix an error caused by detecting the Packer.nvim

- autoload/sessions/session.vim
- plugin/dashboard.vim
potential fix for issue #42 (windows specific fixes).
1. Proper path separators for windows and linux.
2. SessionSave without argument will save a session with current buffer name.
3. SessionLoad without argument loads most recent session sorted by time.
> fix: SessionSave, SessionLoad

- plugin/dashboard.lua
Most likely a copy-paste mistake during the rewrite.
The problem here is that I'm not sure what to "restore" it to. I actually use `1` myself, and it's the default in Neovim AFAIK, but I decided not to change the number used here.
Perhaps we should store the value used before Dashboard in a variable and restore that value back afterwards.
Another way is to just not change this setting at all:
1. By default it should be `1`, which hides it when only one tab is open.
2. If Dashboard opens at boot, you don't see it anyway.
3. If user changes it to `2` manually, then they probably *want* to see the tabbar even on the dashboard on start.
4. Opening a new tab and manually opening the dashboard on that tab probably shouldn't hide the tabbar.
> Restore showtabline after leaving dashboard

- lua/dashboard/preview.lua
This should really fix #175 as a previous fix would only work for users of `packer` nvim plugin manager.
> Fix for #175

- lua/dashboard/events.lua
A simple fix for https://github.com/glepnir/dashboard-nvim/issues/197 there might be smarter solution but idk, from my short testing it seems that nvim_del_augroup_by_id doesnt accept nil on nvim-qt
> Fix for issue #197

- lua/dashboard/events.lua
- lua/dashboard/init.lua
This PR should fix the `winbar` not reappearing after opening a new or existing file via the dashboard menu.
> Fix winbar not reappearing after opening a file 

- lua/dashboard/theme/doom.lua
The doom theme was assuming all `action` entries were a string. Fixes #267
> Fix actions that are a lua function causing an error with doom theme

- README.md
The example config of doom will lead to an error:
```
E5113: Error while calling lua chunk: vim/_init_packages.lua:0: /Path/plugin-config/dashboard.lua:31: '}' expected (to close '{' at line 9) near 'footer'
stack traceback:
[C]: in function 'error'
vim/_init_packages.lua: in function <vim/_init_packages.lua:0>
[C]: in function 'require'
```
This pr will add the missing ','
> Fix: fix example code snippet

- lua/dashboard/theme/hyper.lua
When using some Nerd Font like 󰏔(`\udb80\udfd4`), the shortcut highlight not work as expect.
`nvim --version` output:
```
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey
Features: +acl +iconv +tui
```
> hyper: fix shortcut highlight

- lua/dashboard/theme/hyper.lua
This PR fixed the bug that in hyper theme it's failed to open a file with spaces in its path.
I tried to open file with spaces in its path in the mru list and failed:
```error
E5108: Error executing lua: .../packer/opt/dashboard-nvim/lua/dashboard/theme/hyper.lua:187: attempt to concatenate local 'path' (a nil value)
stack traceback:                                                                                                                                                                          
.../packer/opt/dashboard-nvim/lua/dashboard/theme/hyper.lua:187: in function <.../packer/opt/dashboard-nvim/lua/dashboard/theme/hyper.lua:176>
```
So I tried to fix it. It works on my PC (Ubuntu 20.04). Not tested on Windows.
> Fix: in hyper theme failed to open a file with spaces in its path

- README.md
In the readme hyper config example, a missing ',' (comma) was found in the config project field.
> Chore: add missing comma in readme hyper config example

- lua/dashboard/theme/doom.lua
```lua
local col = line:find('%w')
if col then
col = col - 1
else
col = 0
end
```
Added this change and removed all lines that use `col - 1`.
This made it possible to do this
```lua
require("dashboard").setup {
theme = 'doom',
config = {
header = opts.header,
footer = { opts.footer },
center = {
{
desc = '',
},
},
}
}
```
A small note is that some the cursor is visible and all the way on the left and I can't figure out where to place the cursor. I've been looking for ways to hide the cursor, this should probably be in a separate issue or discussion.
> Allowed for `config.center.desc = ''`

- lua/dashboard/init.lua
It's an error when applying 'Dashboard' in opened buffer:
```vim
Error executing vim.schedule lua callback: ...al/share/nvim/lazy/dashboard-nvim/lua/dashboard/init.lua:213: attempt to index field 'opts' (a nil value)
stack traceback:
...al/share/nvim/lazy/dashboard-nvim/lua/dashboard/init.lua:213: in function 'load_theme'
...al/share/nvim/lazy/dashboard-nvim/lua/dashboard/init.lua:273: in function 'callback'
...al/share/nvim/lazy/dashboard-nvim/lua/dashboard/init.lua:192: in function ''
vim/_editor.lua: in function <vim/_editor.lua:0>
```
> fix(init.lua): attempt to index field 'opts' (a nil value)

- lua/dashboard/theme/doom.lua
- lua/dashboard/theme/hyper.lua
- lua/dashboard/utils.lua
This PR adds additional info to the dashboard when using lazy.nvim
Added:
- Startuptime
- Number of plugins loaded vs total
Thoughts:
- Could we display similar info when using packer.nvim?
- Display `Startuptime` only when displaying Dashboard at startup?
Let me know what you think.
> Feat: added additional plugins info when using lazy.nvim

- lua/dashboard/theme/doom.lua
I use [auto-session](https://github.com/rmagatti/auto-session) to restore previous session.  If I execute restore too quickly after dashboard is displayed it will produce error like in #364 and #339. 
PR checks bufnr before creating autocmd, which is using the nonexistent buffer id of 1 producing the error.
> fix: checks if current buffer = config.bufnr before creating autocmd

- lua/dashboard/theme/hyper.lua
Stacktrace:
The paths string from cache looks like below somehow
```
"return { \"/Users/username/lexical/projects/lexical_plugin\", \"/Users/username/lexical/apps/protocol\", \"/Users/username/lexical\
", \"/Users/username/lexical/projects/lexical_shared\", \"/Users/username/dotfiles\" }\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
```
I recently upgraded to `MacOS Ventura 13.4`, not sure if it's related tho. Also don't find any thing fishy in the `project_delete` function. Hence, do some clean up before `loadstring` of the data.
> Trailing null char (`\0`) in cache leading to crash

- lua/dashboard/theme/hyper.lua
- lua/dashboard/utils.lua
there seems to be a problem with displaying some of the devicons, especially overrides with multidot extensions like `.module.ts`, this makes sure the proper mechanism of `nvim-web-devicons` is utilized to retrieve the longest matching extension from the filename
before
after
> fix: display devicons properly

- lua/dashboard/theme/hyper.lua
Fixes bug mentioned in: #375
Previous version of the `letter_hotkey` function caused the editor to freeze once all hotkeys a-z were exhausted.
This commit fixes the bug by introducing better way to generate random hotkeys for the "project" and "mru" entries.
> Fix broken hotkey generation

- lua/dashboard/theme/hyper.lua
Currently, after all letters are exhausted, the hotkey generation falls back to generation numbers.
This commit changes it slightly, so that the uppercase keys generate after the lowercase ones:
Before the hotkey generation change there was no uppercase keys and that's why I put it as TODO in the #382 commit.
If you like this change go ahead and merge the it and if you don't, feel free to close it and remove the original TODO from the generate_letter function :)
> Add uppercase letters for hotkey generation

- doc/dashboard.txt
- lua/dashboard/theme/doom.lua
This makes the `key` value format configurable for the `doom` theme through the `key_format` property. E.g. use case included in docs.
Thought about putting the config prop at a higher level so the same format is applied to all, but decided on the per-item config because it's more consistent and flexible.
> feat(doom): configurable key_format property

- README.md
So yesterday when I submitted the `key_format` change I'd updated `doc/dashboard.txt` directly without realizing that was auto-generated from `README.md` by gh action (I thought it was the other way around). So obviously my doc changes got overridden :P.
This should correct that.
> chore(doom): add key_format config docs

- .luarc.json
- README.md
- doc/dashboard.txt
- lua/dashboard/theme/hyper.lua
This adds a new `cwd_only` option to limit the Most Recent File list to the `cwd`, defaulted to `false` to preserve current plugin behaviour.
> feat(hyper): option to limit mru list to cwd

- lua/dashboard/theme/hyper.lua
- if is relative path, get the correct `scol`
- also to escape the path to handle some filename edge case, for eg `*foo.txt`
> fix: handle filename start with dot

- lua/dashboard/theme/doom.lua
This should fix #422. There is a problem with multibyte charsets (like some nerd-fonts icons), cause Lua count the bytes and not the chars of a string (At least with [Lua 5.2](https://www.lua.org/manual/5.2/manual.html#2.1)). In this case, even if `col` is the correct position, its not counting the extra byte of the icon character.
This PR adds a `delta` value that would insert an offset to the `col` value when needed.
Regards
> fix(doom): Adjust cursor position for multibyte charsets in menu entry

- lua/dashboard/theme/doom.lua
This should be a better approach than my previous PR (#424). The problem was that if icon strings with other than two characters where used, the cursor would be incorrectly positioned. Now it works when the user has no icons or uses widths other than two characters (`"c "`). For example: `"c"`, `"c "`, `"c "`, etc.
Regards
> fix(doom): Fix cursor position for menu entries with other than 2 chars

- lua/dashboard/theme/doom.lua
This PR refactors the `keymap.set` call in the Doom theme, aligning it with the code from Hyper and incorporating descriptions from `entry.desc` into the `opts` table of the `keymap.set` function. So, when users explore their keymaps values, such as in the `:Telescope keymaps` picker, they will see meaningful descriptions instead of `<anonymous>`.
> docs(doom): Add descriptions to autogenerated keymaps

- lua/dashboard/theme/hyper.lua
> Fix when passing shortcut = {} to config of theme Hyper

- README.md
- lua/dashboard/theme/doom.lua
- lua/dashboard/theme/hyper.lua
- lua/dashboard/utils.lua
#438 
Slow requests, such as network requests, to fetch the footer content slows the dashboard and makes its startup time unreliable !
A command to update the footer `DashboardUpdateFooter`
It takes in consideration the last number of lines of the last footer (declared via config or via the command) to know how to update the footer
> feat: add editor command DashboardUpdateFooter

- lua/dashboard/events.lua
solve issue #385 on windows
The permissions mode 438 (0666) should not be used for private files inside `$HOME`, thus 384 (0600).
This is not critical though.
The real issue is the old "rs+" parameter.
> Update events.lua: change invalid open-file flags rs+ to r+

- lua/dashboard/theme/doom.lua
Opening netrw after opening dashboard on startup:
```
Error executing lua callback: ...ckstart/lazy/dashboard-nvim/lua/dashboard/theme/doom.lua:133: attempt to index local 'curline_str' (a nil value)
stack traceback:
...ckstart/lazy/dashboard-nvim/lua/dashboard/theme/doom.lua:133: in function <...ckstart/lazy/dashboard-nvim/lua/dashboard/theme/doom.lua:119>
Error executing lua callback: ...ckstart/lazy/dashboard-nvim/lua/dashboard/theme/doom.lua:133: attempt to index local 'curline_str' (a nil value)
stack traceback:
...ckstart/lazy/dashboard-nvim/lua/dashboard/theme/doom.lua:133: in function <...ckstart/lazy/dashboard-nvim/lua/dashboard/theme/doom.lua:119>
Error executing lua callback: ...ckstart/lazy/dashboard-nvim/lua/dashboard/theme/doom.lua:133: attempt to index local 'curline_str' …
```
> bugfix: make sure current buffer is dashboard

- plugin/dashboard.lua
As this plugin now uses StdinReadPre, user shouldn't lazy-load this plugin
Fix #443
> fix(plugin): don't load if read from stdin

- lua/dashboard/init.lua
Currently, if the user has `opts.hide.statusline` or `opts.hide.tabline` enabled, as long as a dashboard buffer exists, the user's UI components will stay hidden.
This results in the following workflow behaving strangely:
1. Open neovim to show dashboard
- If you chose to hide tabline/statusline, they will be hidden to get a clean look 
2. Run a command that creates a new tab (e.g. "DiffViewOpen"), or create a tab yourself
3. Watch as contents are filled in the new tab, but you still have your tabline/statusline hidden
This PR stores the user's UI preferences when starting a dashboard, and restores the user's UI settings every time he/she switches to a tab where there's no dashboard buffer visible.
Before (no tabline/statusline after running `DiffViewFileHistory`):
After (the expected …
> Restore user's UI options when switching tabs

- lua/dashboard/theme/hyper.lua
This pull request addresses an issue in the MRU (Most Recently Used) file filtering logic, where files outside the current working directory (cwd) could incorrectly be included. The previous implementation relied on a substring match, which caused files with similar directory prefixes to be incorrectly identified as being within the cwd.
For example, if the `cwd` is `/foo/bar` and a file is located at `/foo/barrrr/baz`, the previous implementation would incorrectly include `/foo/barrrr/baz` as being within `/foo/bar` due to a partial substring match.
> fix: accurately identify files within current working directory for MRU filtering

- lua/dashboard/init.lua
So, #455 restored the user's settings when switching tabs, but was missing the check for the hiding setting being enabled in the first place. This attempts to solve it.
Thanks for bringing it up, and sorry for briefly breaking some configs.
> fix: restore user's UI options when switching tabs 2

- lua/dashboard/theme/doom.lua
This PR Fix issue #461
For some reason, `vim.api.nvim_strwidth` returns a larger width after resizing
at certain small window sizes. This PR adds a check for negative values in
`offset` and sets it to zero in those cases.
Seems like an upstream bug with nvim_strwidth.
> fix(doom): Correct negative offset when resizing terminal

- lua/dashboard/theme/hyper.lua
If a user has `vim.o.shellslash` enabled slash usage on windows can get a bit weird. `uv.cwd` returns `\` while the filepaths in mru will contain `/`.
The aim of this PR is to solve this issue by instead of defaulting to backslash on windows, get the separator from the first item of mru, and use that as separator in `cwd_with_sep`
> fix(hyper): handle backslash and slash regardles of os in cwd

- README.md
- lua/dashboard/init.lua
- lua/dashboard/theme/hyper.lua
I for one always hate the randomize `shortcut`. It breaks my workflow to have to read which key to press.
So, this PR add option `shuffle_letter` option to `hyper` theme so we can have fixed/ordered shortcut.
Set `shuffle_letter = false` in hyper `config` for fixed/ordered `shortcut` 
Closes #374, closes #439
> Option for fixed/alphabetical `shortcut` ordering for `hyper` theme

- lua/dashboard/init.lua
Issue: `opts.hide.winbar` doesn't work
Seems like a buffer-local value of `winbar = ''` doesn't override a global non-empty winbar value. To see this:
```
nvim --clean
set winbar=foo
split
setlocal winbar=
```
This PR changes `opts.hide.winbar` to use `save_user_options`/`set_ui_options`/`restore_user_options`.
> Fix `opts.hide.winbar`

- lua/dashboard/theme/doom.lua
Fix #465
Some multiwidth/multibyte chars return valid negative offsets from `nvim_strwidth`. This PR address them and also ensure that no negative col values are passed directly into the `vim.api.nvim_win_set_cursor` pos col arg.
> fix(doom): Never set a negative column cursor position

- lua/dashboard/theme/hyper.lua
On hyper theme's mru, fix a bug where the plugin would crash if config.project.icon was a string with only whitespace characters
> Fix bug where plugin would crash if icon was empty

- README.md
- lua/dashboard/theme/hyper.lua
Adds a new option to the config `mru.enable` to allow both the Project and Recent Files sections to be removed from the dashboard. 
Resolves #420
> feat(hyper): add `mru.enable` option

- README.md
- lua/dashboard/theme/doom.lua
- Vertically center the Doom dashboard.
- Doom code refactor.
- Add the `config.vertical_center` option (defaults to `false`).
- Same average load time on my system.
- Fix #354. 
Is working for me without any problem in a lot of config scenarios, but I think it needs more testing.
Since this use the same `load_packages` code from `hyper`, but with a return, maybe we could move that into `utils` or something like `theme/packages`?
Regards
> feat(doom): Add vertical center

- lua/dashboard/utils.lua
This PR updates the utility module to use the officially recommended `vim.validate()` form 1 syntax, as per Neovim 0.11+ guidelines.
neovim v0.11 deprecate info docs => [https://neovim.io/doc/user/deprecated.html#_deprecated-in-0.11](https://neovim.io/doc/user/deprecated.html#_deprecated-in-0.11)
- Replaced deprecated `vim.validate({ key = { value, 'type' } })` (form 2)
- Applied `vim.validate('name', value, 'type')` (form 1) in:
- `get_max_len()`
- `center_align()`
- Neovim 0.11 deprecates form 2 of `vim.validate()`
- There's bunch of deprecate warnings appear in `:checkhealth vim.deprecated`.
No functional changes, purely an internal cleanup to keep the codebase compatible and modern.
> refactor(utils): Use vim.validate() form 1 for Neovim 0.11 compatibility

- lua/dashboard/utils.lua
* This function will dynamically use the correct validate method based on the neovim version.
* This addresses the issue reported here which makes the newer validate method breaks the plugin on neovim versions < 0.11:  [https://github.com/LazyVim/LazyVim/issues/6000](https://github.com/LazyVim/LazyVim/issues/6000)
NOTE: I only tested this on my machine which has neovim version 0.11. But hopefully should work on older neovim versions now (as long as the `vim.version().minor` returns the expected output).
> feat(utils): Add a helper to handle vim.validate for tables

- lua/dashboard/theme/hyper.lua
In the Hyper theme, this PR updates the `confirm_key` option to accept an array of strings instead of just a single string.  
It also removes any keys specified in `confirm_key` from the `letter_list`.
```lua
-- in options
confirm_key = 'o' -- or { 'o', '<CR>' }
```
> feat(hyper): support multiple confirm_keys and exclude them from letter_list

- lua/dashboard/theme/hyper.lua
I set the "cwd_only" option to true in the hyper theme but the Most Recent Files list would not be populated correctly, it only showed one entry called "empty files". 
The issue was being caused by path separator inconsistencies between 'cwd' and file paths, which would return an empty list when the filter was applied. I have fixed this issue by properly normalizing and comparing paths. mlist is now correctly populated with only recent files from the cwd if cwd_only is set to true.
> Fix hyper showing empty mru_list if cwd_only set to true

- plugin/dashboard.lua
fixes https://github.com/nvimdev/dashboard-nvim/issues/475
The `StdinReadPre` autocmd doesn't seem to set the `vim.g.read_from_stdin` variable, which means when you run something like the following:
```shell
echo "hello world!" | nvim -
```
The dashboard will override initial buffer and the `hello world!` will be lost.
I've changed this autocmd to `VimEnter` and now it will check for the `-` arguement in the arguments list to determine if nvim is reading from stdin.
> fix: correctly handle stdin

- lua/dashboard/init.lua
- lua/dashboard/theme/hyper.lua
- plugin/dashboard.lua
Allow displaying shortcuts on the left side in the hyper theme.
```lua
opts = {
...
shortcuts_left_side = true, -- if true, display on the left side
...
}
```
> feat(hyper): display shortcuts on the left side
