autoload/dashboard.vim
Hi, thanks for the plugin, loving it!
Right now the plugin will break if not using any plugin manager, this PR just add a small adjustment to it.
=> fix error when not using plugin manager

README.md, autoload/dashboard/handler.vim, autoload/dashboard/section.vim, doc/dashboard.txt, plugin/dashboard.vim
Hi :) I like your plugin a lot, sometimes I need to quickly get a clean buffer, so I added this small change.
=> Add 'New File' to dashboard

autoload/dashboard/section.vim
Small fix for custom shortcut icons
=> Custom shortcut icon: extend correct variables

README.md
Add missing variable for config example.
=> Add missing variable

autoload/dashboard.vim, autoload/dashboard/preview.vim, plugin/dashboard.vim
Now can use temrinal command to preview something like cat or other commands.
=> add preview support

autoload/dashboard/section.vim
Sorry, I think I screwed up the text alignment in my previous commit. Also I found another small bit of text that could do with a change.
=> Fix text alignment and minor text change

README.md
Fix 404 not found in the README.md.
Thank you.
=> Fix not found document file

doc/dashboard.txt
=> Doc: fixed doc errors

doc/dashboard.txt
The original line causes the following error:
```
Error detected while processing function dashboard#instance[73]..dashboard#utils#draw_center:
line    1:
E896: Argument of map() must be a List, Dictionary or Blob
E712: Argument of max() must be a List or Dictionary
```
When using the fixed version, the result is as expected
=> Fix example in doc (g:dashboard_custom_footer)

README.md
Initially just some typo fixes. However, cleaned up some English usage and formatting as well. Hope its okay!
=> chore: small README.md updates

README.md
=> fix typo in README.nd

README.md
=> fix(doc): fix doc

README.md
improper way of getting deps via packer. caused issue #247
=> doc: fix bad packer call

lua/dashboard/theme/hyper.lua, lua/dashboard/utils.lua
fix #42
not test on linux.
`is_win` is modified since the previous solution not works on win10.
=> fix file open issue for hyper

README.md, lua/dashboard/init.lua, lua/dashboard/theme/hyper.lua
i want to custom action in project, like    
``` lua
project = {
action = function(path)
vim.fn.chdir(path)
require('telescope').extensions.frecency.frecency({ workspace = 'CWD' })
end
}
```
i think frecency more useful than find_files
=> feat:hyper theme project action support function

README.md
Saw some typos in line 227 in the readme.
=> Fixed typos and grammar

README.md, doc/dashboard.txt, lua/dashboard/theme/hyper.lua
See the following links for more information:
- https://github.com/ryanoasis/nerd-fonts/issues/365
- https://github.com/ryanoasis/nerd-fonts/issues/1059#issuecomment-1404891287
=> fix(icons): match new Nerd Fonts 3.0.0 release

README.md
- DashboardShotCut > DashboardShortCut
- DashboardShotCutIcon > DashboardShortCutIcon
=> docs(README): fix spelling for highlight groups

lua/dashboard/preview.lua
A more general approach to controlling the timing of preview window closure.
execute `belowright terminal`
execute `belowright terminal`
=> fix: make preview have same lifetime with dashboard buffer

README.md
Got a bunch of notifications in the console while trying to install this. Not fatal I guess but should be fixed for newer users.
=> Update plugin repo path in documentation

lua/dashboard/theme/hyper.lua
this should fix https://github.com/nvimdev/dashboard-nvim/issues/417
checking only 
```javascript
if config.mru.cwd_only then
```
would cause error on selecting recent project by entering the wrong path
also enhance the scenario when user presses enter on empty space
=> fix: error opening recent projects

plugin/dashboard.lua
https://github.com/nvimdev/dashboard-nvim/issues/440
=> fix: restore session with empty file, display Dashboard

lua/dashboard/init.lua
Reverts nvimdev/dashboard-nvim#455
=> Revert "Restore user's UI options when switching tabs"

lua/dashboard/preview.lua
=> fix: add type check for winconfig.col
